apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: labs-db
spec:
  version: "11.2"
  storageType: Durable
  storage:
    storageClassName: "nfs-sc"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Resume
