apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: labs-mysql
spec:
  version: "8.0.3"
  storageType: Durable
  storage:
    storageClassName: "nfs-sc"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Resume
