apiVersion: apps/v1
kind: Deployment
metadata:
  name: labs-deployment
  labels:
    app: labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labs
  template:
    metadata:
      labels:
        app: labs
    spec:
      containers:
      - name: django
        image: pwpon500/labs_challenge
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: labs-svc
spec:
  selector:
    app: labs
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: labs-ingress
  labels:
    traffic-type: external
spec:
  rules:
  - host: labs.walthome.duckdns.org
    http:
      paths:
      - path: /
        backend:
          serviceName: labs-svc
          servicePort: 80